name: Deploy

# Controls when the action will run. 
on: push # Adjust branch as needed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install npm dependencies and run tests
        run: |
          cd C:\Users\prospectbddev\Desktop\auto-deploy
          git pull origin
