name: Windows Deployment

on: push

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (Optional)
        run: |
          cd C:\Users\prospectbddev\Desktop\auto-deploy
          git pull origin

