name: Deploy

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Save the SSH private key to a file
        echo "${{ env.SSH_PRIVATE_KEY }}" > ssh_key
        # Use OpenSSH to execute commands over SSH
        ssh -i ssh_key -l ${{ secrets.USERNAME }} -p 22 ${{ secrets.HOST }} "cd  C:\Users\prospectbddev\Desktop\auto-deploy && git pull origin main"
