name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Save the SSH private key to a file
        echo "${{ env.SSH_PRIVATE_KEY }}" > ssh_key
        # Use plink to execute commands over SSH
        plink -ssh -i ssh_key -l ${{ secrets.USERNAME }} -P 22 ${{ secrets.HOST }} "cd /var/www/youtube.com/ && git pull origin main && git status && npm install --only=prod"
